#!/bin/bash
set -ouex pipefail

# Repository setup
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list
curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc
tee /etc/apt/sources.list.d/zabbly-incus-stable.sources <<EOF
Enabled: yes
Types: deb
URIs: https://pkgs.zabbly.com/incus/stable
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: main
Signed-By: /etc/apt/keyrings/zabbly.asc
EOF

# Initial update
apt-get update -y

# Oxidize
apt install -y \
	rust-coreutils \
	sudo-rs

mv -f /usr/bin/sudo-rs /usr/bin/sudo
mv -f /usr/bin/visudo-rs /usr/bin/visudo
mv -f /usr/bin/su-rs /usr/bin/su

# Current sudo-rs package is broken in trixie
# https://github.com/trifectatechfoundation/sudo-rs?tab=readme-ov-file#debian
chmod u+s /usr/bin/su

# Replace coreutils with their rust counterpart
#for src_file in /usr/lib/cargo/bin/coreutils/*; do
#	ln -s "/usr/bin/coreutils" "/usr/bin/$(basename "$src_file")-link"
#	mv -f "/usr/bin/$(basename "$src_file")-link" "/usr/bin/$(basename "$src_file")"
#done

# Distrobox
apt-get install -y \
	podman \
	distrobox

# Flatpak & Flathub
apt-get install -y \
	flatpak \
	curl

mkdir -p /etc/flatpak/remotes.d
curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo

# Brew Tap
mkdir -p /usr/share
curl "$(curl https://api.github.com/repos/frostyard/homebrew-tap/releases/latest | jq -r --arg arch "$(uname -m)" '.assets[] | select(.name | test(".*-" + $arch + "\\.tar\\.zst$")) | .browser_download_url')" -Lo /usr/share/homebrew.tar.zst

# Docker
apt-get install -y \
	docker-ce \
	docker-ce-cli \
	containerd.io \
	docker-buildx-plugin \
	docker-compose-plugin

# Incus
apt-get install -y \
	dnsmasq-base \
	ovmf \
	qemu-kvm \
	qemu-utils \
	qemu-system-gui \
	qemu-system-modules-spice \
	ipxe-qemu \
	genisoimage \
	virt-viewer \
	incus \
	incus-ui-canonical

# GNOME Customization
apt-get install -y \
	gnome-shell-extension-appindicator

# locales and keyboard
apt-get install -y \
    locales \
    keyboard-configuration

# NetworkManager
apt-get install -y \
    network-manager \
    network-manager-applet

# Switch to IWD
apt-get install -y \
	iwd
apt-get remove -y \
	wpasupplicant

# Shell Alternatives
apt-get install -y \
    fish \
	zsh

# Vim
apt-get install -y \
	vim \
	netcat-traditional

apt-get install -y \
	systemd-homed \
	openssh-server

# Cleanup unwanted packages
apt-get purge -y \
	wpasupplicant \
	gnome-initial-setup \
	gnome-tour

# Add mokutil for Surface hardware during install
apt-get install -y \
	mokutil

# Grab latest surface linux secure boot key, this will be enrolled during install if snowfield is selected.
mkdir -p /usr/share/linux-surface-secureboot
curl https://github.com/linux-surface/linux-surface/raw/refs/heads/master/pkg/keys/surface.cer -Lo /usr/share/linux-surface-secureboot/surface.cer

# Create mountpoint for users that want this feature.
mkdir -p /nix

apt list --installed > /usr/share/snow/snow.packages.txt

# Disable systemd-homed firstboot service, let installer create user
systemctl disable systemd-homed-firstboot.service
systemctl mask systemd-homed-firstboot.service

# Update os-release info
sed -i 's/^PRETTY_NAME=.*/PRETTY_NAME="Snow Linux"/' /usr/lib/os-release
sed -i 's/^NAME=.*/NAME="Snow Linux"/' /usr/lib/os-release
echo "ID_LIKE=debian" >> /usr/lib/os-release

# Ensure first boot works
rm -rf /etc/machine-id
