#!/bin/bash
set -ouex pipefail

# Repository setup
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list
curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc
tee /etc/apt/sources.list.d/zabbly-incus-stable.sources <<EOF
Enabled: yes
Types: deb
URIs: https://pkgs.zabbly.com/incus/stable
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: main
Signed-By: /etc/apt/keyrings/zabbly.asc
EOF
tee /etc/apt/sources.list.d/debian-backports.sources > /dev/null <<EOF
Types: deb deb-src
URIs: http://deb.debian.org/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")-backports
Components: main non-free-firmware
Enabled: yes
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF

# Initial update
apt-get update -y

# Distrobox
apt-get install -y \
	podman \
	distrobox

apt-get install -y \
	systemd-container

# Flatpak & Flathub
apt-get install -y \
	flatpak \
	curl
mkdir -p /etc/flatpak/remotes.d
curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo

# Docker
apt-get install -y \
	docker-ce \
	docker-ce-cli \
	containerd.io \
	docker-buildx-plugin \
	docker-compose-plugin

# Incus
apt-get install -y \
	dnsmasq-base \
	ovmf \
	qemu-kvm \
	qemu-utils \
	qemu-system-gui \
	qemu-system-modules-spice \
	ipxe-qemu \
	genisoimage \
	virt-viewer \
	incus \
	incus-extra \
	incus-ui-canonical

# GNOME Customization
apt-get install -y \
	gnome-shell-extension-appindicator

# locales and keyboard
apt-get install -y \
    locales \
    keyboard-configuration

# NetworkManager
apt-get install -y \
    network-manager \
    network-manager-applet \
	iwd
apt-get remove -y \
	wpasupplicant

# Shell Alternatives
apt-get install -y \
    fish \
	zsh
rm -f /usr/share/applications/fish.desktop

# Add Vim
apt-get install -y \
	vim \
	netcat-traditional \
	openssh-server

# Add cifs-utils for samba shares
apt-get install -y \
	cifs-utils

# Cleanup unwanted packages
apt-get purge -y \
	wpasupplicant \
	gnome-initial-setup \
	gnome-tour

# Add build-essential
apt-get install -y \
	build-essential

# Grab latest surface linux secure boot key, this will be enrolled during install if snowfield is selected.
mkdir -p /usr/share/linux-surface-secureboot
curl https://github.com/linux-surface/linux-surface/raw/refs/heads/master/pkg/keys/surface.cer -Lo /usr/share/linux-surface-secureboot/surface.cer

# Install Backports Kernel and Firmware
codename=$( . /etc/os-release && echo "$VERSION_CODENAME" )
echo "firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true" | debconf-set-selections
echo "firmware-ivtv firmware-ivtv/license/accepted boolean true" | debconf-set-selections
apt-get purge -y \
	"linux-image-$(dpkg --print-architecture)"
rm -rf /usr/lib/modules/*
apt-get install -y -t "${codename}-backports" \
	"linux-image-$(dpkg --print-architecture)" \
	atmel-firmware \
	bluez-firmware \
	dahdi-firmware-nonfree \
	mesa-vulkan-drivers \
	mesa-va-drivers \
	intel-media-va-driver-non-free \
	firmware-amd-graphics \
	firmware-ast \
	firmware-ath9k-htc \
	firmware-atheros \
	firmware-bnx2 \
	firmware-bnx2x \
	firmware-brcm80211 \
	firmware-carl9170 \
	firmware-cavium \
	firmware-cirrus \
	firmware-intel-graphics \
	firmware-intel-misc \
	firmware-intel-sound \
	firmware-ipw2x00 \
	firmware-ivtv \
	firmware-iwlwifi \
	firmware-libertas \
	firmware-linux-free \
	firmware-linux-nonfree \
	firmware-linux \
	firmware-marvell-prestera \
	firmware-mediatek \
	firmware-misc-nonfree \
	firmware-myricom \
	firmware-netronome \
	firmware-netxen \
	firmware-nvidia-graphics \
	firmware-qlogic \
	firmware-realtek \
	firmware-siano \
	firmware-sof-signed \
	firmware-zd1211

# Print final package list
apt list --installed > /usr/share/snow/snow.packages.txt

# Update os-release info
sed -i 's/^PRETTY_NAME=.*/PRETTY_NAME="Snow Linux"/' /usr/lib/os-release
sed -i 's/^NAME=.*/NAME="Snow Linux"/' /usr/lib/os-release
sed -i 's/^ID=.*/ID="snow"/' /usr/lib/os-release
echo "ID_LIKE=debian" >> /usr/lib/os-release

# Update build information in os-release
sed -i "s/^BUILD_ID=.*/BUILD_ID=\"$BUILD_ID\"/" /usr/lib/os-release

# Move Incus to /usr/share/factory/opt/incus
# so we can symlink /opt/incus to it via tmpfiles.d
# and avoid issues with /var/opt being mounted on top
mkdir -p "/usr/share/factory/opt/incus"
mv /opt/incus /usr/share/factory/opt/

# write the current date to a file in /etc to indicate when the build was made
date -u +"%Y-%m-%dT%H:%M:%SZ" > /etc/snow_build_date